unbind r
bind r source-file ~/.tmux.conf

set -g prefix BTab

set-option -g status-position bottom 
set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"

setw -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 's'
set -g @sessionx-custom-paths '~/Projects/'
set -g @sessionx-custom-paths-subdirectories 'true'
set -g @sessionx-filter-current 'false'
set -g @sessionx-window-mode 'on'
set -g @sessionx-tree-mode 'off'
set -g @sessionx-preview-enabled 'true'

run '~/.tmux/plugins/tpm/tpm'
